# Generated by Django 4.0.3 on 2022-04-09 10:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('language', models.CharField(choices=[('russian', 'Russian'), ('english', 'English')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('englishText', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='englishText', to='main_api.text')),
                ('russianText', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='russianText', to='main_api.text')),
            ],
        ),
    ]
