# Generated by Django 4.0.3 on 2022-04-09 21:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0002_category_text_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accent',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('link', models.URLField()),
                ('speaker_name', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('accent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_api.accent')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_api.category')),
            ],
        ),
    ]
